
It's all fun and games untill you realise you are working for free



* ten step process




*  An essay is about me attempting to explore a subject and gain some understanding on it


* The reason I should start writing an essay is so that I can formulate a coherant, informed and sophisticated set of ideas regarding something of importance

* writing can clarify my thoughts and strengthen my memory

* with writing I can interrogate ideas and thoughts, rearrange them, remove, add to them to make them stronger. I can also learn to reject ideas that are possibly substandard

*

The ideas for this exhibition began as a way for me to question how to display so many pieces of work I was making. Not in a way that I am prolific, but more in a way where I seemed to be churning through tutorial after tutorial in a manner to attempt to teach myself how to program by using graphics as a way of learning. I found myself working through tutorial after tutorial in a way that would help me memorise techniques etc whilst all the time producing image after image, animation after animation. My thoughts kept leading me to  "If I'm ever to display these in a gallery, how am I supposed to do that?" 


